version: "3"
services:
  sonarqube:
    image: sonarqube:7.1-alpine
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
       SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
       SONARQUBE_JDBC_USERNAME: sonar
       SONARQUBE_JDBC_PASSWORD: sonar
    restart: always
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./sonarqube_opt/:/opt/sonarqube_opt/
    command: -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m

  db:
    image: postgres:10.5-alpine
    networks:
      - sonarnet
    environment:
       POSTGRES_DB: sonar
       POSTGRES_USER: sonar
       POSTGRES_PASSWORD: sonar
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge


